//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionProductions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompositionProductions()
        {
            this.StageProductions = new HashSet<StageProductions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> NomenclatureId { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string Unit { get; set; }
        public Nullable<int> SpecificationId { get; set; }
    
        public virtual Nomenclatures Nomenclatures { get; set; }
        public virtual OrderProductions OrderProductions { get; set; }
        public virtual Specifications Specifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StageProductions> StageProductions { get; set; }
    }
}
