//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionBrigades
    {
        public int Id { get; set; }
        public Nullable<int> BrigadeId { get; set; }
        public Nullable<int> WorkerId { get; set; }
    
        public virtual Brigades Brigades { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
