//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionSales
    {
        public int Id { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> NomenclatureId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Count { get; set; }
        public Nullable<decimal> Sum { get; set; }
    
        public virtual Nomenclatures Nomenclatures { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
