//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborSpecifications
    {
        public int Id { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> WorkTypeId { get; set; }
        public Nullable<int> CountMinut { get; set; }
    
        public virtual StageSpecifications StageSpecifications { get; set; }
        public virtual WorkTypes WorkTypes { get; set; }
    }
}
