//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSpecifications
    {
        public int Id { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string Unit { get; set; }
        public Nullable<int> NomenclatureId { get; set; }
    
        public virtual Nomenclatures Nomenclatures { get; set; }
        public virtual Nomenclatures Nomenclatures1 { get; set; }
        public virtual StageSpecifications StageSpecifications { get; set; }
    }
}
