//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalBusinessOpportunitiesEntities : DbContext
    {
        public DigitalBusinessOpportunitiesEntities()
            : base("name=DigitalBusinessOpportunitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brigades> Brigades { get; set; }
        public virtual DbSet<CompositionBrigades> CompositionBrigades { get; set; }
        public virtual DbSet<CompositionOrderMaterials> CompositionOrderMaterials { get; set; }
        public virtual DbSet<CompositionProductions> CompositionProductions { get; set; }
        public virtual DbSet<CompositionSales> CompositionSales { get; set; }
        public virtual DbSet<CompositionTransfers> CompositionTransfers { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<LaborProductions> LaborProductions { get; set; }
        public virtual DbSet<LaborSpecifications> LaborSpecifications { get; set; }
        public virtual DbSet<MaterialProductions> MaterialProductions { get; set; }
        public virtual DbSet<MaterialSpecifications> MaterialSpecifications { get; set; }
        public virtual DbSet<Nomenclatures> Nomenclatures { get; set; }
        public virtual DbSet<OrderProductions> OrderProductions { get; set; }
        public virtual DbSet<OrderPurchaseMaterials> OrderPurchaseMaterials { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Specifications> Specifications { get; set; }
        public virtual DbSet<StageProductions> StageProductions { get; set; }
        public virtual DbSet<StageSpecifications> StageSpecifications { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TransferWarehouses> TransferWarehouses { get; set; }
        public virtual DbSet<WarehouseBalances> WarehouseBalances { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Workshops> Workshops { get; set; }
        public virtual DbSet<WorkTypes> WorkTypes { get; set; }
    }
}
