//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageSpecifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StageSpecifications()
        {
            this.LaborSpecifications = new HashSet<LaborSpecifications>();
            this.MaterialSpecifications = new HashSet<MaterialSpecifications>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NumberStage { get; set; }
        public Nullable<int> NameStage { get; set; }
        public Nullable<int> SpecificationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaborSpecifications> LaborSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSpecifications> MaterialSpecifications { get; set; }
        public virtual Specifications Specifications { get; set; }
    }
}
