//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessOpportunities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageProductions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StageProductions()
        {
            this.LaborProductions = new HashSet<LaborProductions>();
            this.MaterialProductions = new HashSet<MaterialProductions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CompositionOrderId { get; set; }
        public Nullable<int> NomenclatureId { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string Unit { get; set; }
        public Nullable<int> StageNumber { get; set; }
        public Nullable<int> StageName { get; set; }
        public string Status { get; set; }
        public Nullable<int> WarehouseId { get; set; }
    
        public virtual CompositionProductions CompositionProductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaborProductions> LaborProductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProductions> MaterialProductions { get; set; }
        public virtual Nomenclatures Nomenclatures { get; set; }
        public virtual OrderProductions OrderProductions { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
